// <auto-generated />
namespace LF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removesomerequiredvaluesfromfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removesomerequiredvaluesfromfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201608071343280_Remove some required values from fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
